### ISSUE TITLE
Benchmark against Arrow IO

### ISSUE THREAD

**Issue by raulraja** [colomboe/KIO#2]
Since KIO will compete with the upcoming arrow IO that is Bifunctor and has environment support you may be interested in adding KIO to the set of arrow benchmarks to see how it compares to arrow and the Scala implementations. https://github.com/arrow-kt/arrow/tree/master/modules/benchmarks/arrow-benchmarks-fx/src/jmh/kotlin/arrow/benchmarks

**Comment by colomboe** [comment]
This is very interesting, I was wondering about the KIO performances and how to measure them. These benchmarks could be a very good answer 😄
