### ISSUE TITLE
Contribution

### ISSUE THREAD

**Issue by devcdcc** [colomboe/KIO#7]
Are you still thinking to provide support to this library?
Would you like any contributors?
Thanks :)

**Comment by colomboe** [comment]
Given the release of Arrow 1.0, where all the HKT stuff has been removed and the FX library has been ported on top of the standard kotlinx coroutines, I think that KIO has much less sense now. Maybe it could be useful for someone that wants to write code in ZIO style, or just for learning purposes.

What do you think about this? For what use case are you looking at KIO?
